[workspace]
authors = ["Animesh <animesh.workplace@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "non_coding_scores"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
uv = ">=0.8.15,<0.9"
bedtools = ">=2.31.1,<3"
ucsc-bigwigaverageoverbed = ">=482,<483"
